// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// IntHermiteN_stream_upper_cpp
Rcpp::List IntHermiteN_stream_upper_cpp(const NumericVector& Fi, const NumericVector& fi, const NumericMatrix& Hfi, int K);
RcppExport SEXP _MultiStatM_IntHermiteN_stream_upper_cpp(SEXP FiSEXP, SEXP fiSEXP, SEXP HfiSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Fi(FiSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Hfi(HfiSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(IntHermiteN_stream_upper_cpp(Fi, fi, Hfi, K));
    return rcpp_result_gen;
END_RCPP
}
// IntHermiteN_stream_cpp
Rcpp::List IntHermiteN_stream_cpp(const NumericVector& Fi, const NumericVector& fi, const NumericMatrix& Hfi, int K);
RcppExport SEXP _MultiStatM_IntHermiteN_stream_cpp(SEXP FiSEXP, SEXP fiSEXP, SEXP HfiSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Fi(FiSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Hfi(HfiSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(IntHermiteN_stream_cpp(Fi, fi, Hfi, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiStatM_IntHermiteN_stream_upper_cpp", (DL_FUNC) &_MultiStatM_IntHermiteN_stream_upper_cpp, 4},
    {"_MultiStatM_IntHermiteN_stream_cpp", (DL_FUNC) &_MultiStatM_IntHermiteN_stream_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiStatM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
