# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IntHermiteN_stream_upper_cpp <- function(Fi, fi, Hfi, K) {
    .Call(`_MultiStatM_IntHermiteN_stream_upper_cpp`, Fi, fi, Hfi, K)
}

IntHermiteN_stream_cpp <- function(Fi, fi, Hfi, K) {
    .Call(`_MultiStatM_IntHermiteN_stream_cpp`, Fi, fi, Hfi, K)
}

